### ISSUE TITLE
X96 Mini Plus

### ISSUE THREAD

**Issue by phatbs21** [ngowuys/ngowuys#1]
Xin chào, mình cũng đang sử dụng X96 Mini Plus và đang tìm cách cài armbian. Trong lúc cài thì mình cũng gặp vấn đề armbian chỉ nhận 1gb ram thay vì 2gb ram. 
Lục lọi một hồi trên github thì thấy được cái này:
https://github.com/ophub/amlogic-s9xxx-armbian/issues/132
Nếu bạn đã tìm ra giải pháp rồi thì có thể cho mình xin cách được không ? 
Cảm ơn nhiều

**Comment by nmvkhoi** [comment]
:>> đầu tư dữ v e

**Comment by ngowuys** [comment]
> Xin chào, mình cũng đang sử dụng X96 Mini Plus và đang tìm cách cài armbian. Trong lúc cài thì mình cũng gặp vấn đề armbian chỉ nhận 1gb ram thay vì 2gb ram. Lục lọi một hồi trên github thì thấy được cái này: [ophub/amlogic-s9xxx-armbian#132](https://github.com/ophub/amlogic-s9xxx-armbian/issues/132) Nếu bạn đã tìm ra giải pháp rồi thì có thể cho mình xin cách được không ? Cảm ơn nhiều

Cái đó do Armbian chia qua zram nhé, do lâu rồi không sử dụng nên bạn có thể kiếm trên mạng xem cấu hình ZRAM trên Armbianm, thử sửa file `/etc/default/armbian-zram-config` hoặc `/etc/default/armbian-zramconfig`

**Comment by phatbs21** [comment]
> > Xin chào, mình cũng đang sử dụng X96 Mini Plus và đang tìm cách cài armbian. Trong lúc cài thì mình cũng gặp vấn đề armbian chỉ nhận 1gb ram thay vì 2gb ram. Lục lọi một hồi trên github thì thấy được cái này: [ophub/amlogic-s9xxx-armbian#132](https://github.com/ophub/amlogic-s9xxx-armbian/issues/132) Nếu bạn đã tìm ra giải pháp rồi thì có thể cho mình xin cách được không ? Cảm ơn nhiều
> 
> Cái đó do Armbian chia qua zram nhé, do lâu rồi không sử dụng nên bạn có thể kiếm trên mạng xem cấu hình ZRAM trên Armbianm, thử sửa file `/etc/default/armbian-zram-config` hoặc `/etc/default/armbian-zramconfig`

Cảm ơn bạn nhé, mình vào chỉnh lại thì sửa lỗi thành công rồi
